on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
            
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller ./data_import_tool/import_tool.spec
    # Optionally verify that it works (provided that it does not need user interaction)
  

